[versions]
maven = "3.9.16"
maven-plugin-annotations = "3.15.1"

[libraries]
maven-plugin-api = { module = "org.apache.maven:maven-plugin-api", version.ref = "maven" }
maven-core = { module = "org.apache.maven:maven-core", version.ref = "maven" }
maven-plugin-annotations = { module = "org.apache.maven.plugin-tools:maven-plugin-annotations", version.ref = "maven-plugin-annotations" }
